const fs = require('fs');
function w(file, lines) {
  fs.writeFileSync(file, lines.join('\n') + '\n');
  console.log('OK: ' + file);
}

w('services/itau-boleto.js', [
  "const { getAccessToken, invalidateToken } = require('./itau-auth');",
  "const { callBolecode } = require('./itau-api');",
  "const config = require('../config');",
  "",
  "let nossoNumeroSeq = 1;",
  "",
  "function gerarNossoNumero() {",
  "  const seq = String(nossoNumeroSeq++).padStart(8, '0');",
  "  console.log('[BOLETO] Nosso Numero:', seq);",
  "  return seq;",
  "}",
  "",
  "function formatarValorItau(valor) {",
  "  const num = Math.round(parseFloat(valor) * 100);",
  "  return String(num).padStart(15, '0');",
  "}",
  "",
  "function getDataHoje() {",
  "  const d = new Date();",
  "  return d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0');",
  "}",
  "",
  "function calcularDataVencimento(dias) {",
  "  const d = new Date();",
  "  d.setDate(d.getDate() + dias);",
  "  return d.getFullYear() + '-' + String(d.getMonth()+1).padStart(2,'0') + '-' + String(d.getDate()).padStart(2,'0');",
  "}",
  "",
  "function montaPayloadBolecode(dados) {",
  "  const idBeneficiario = config.banco.idBeneficiario || '776400223389';",
  "  const codigoCarteira = config.banco.codigoCarteira || '109';",
  "  const nossoNumero = dados.nossoNumero || gerarNossoNumero();",
  "  let dataVencimento = dados.dataVencimento || calcularDataVencimento(30);",
  "  if (dados.dataVencimento) {",
  "    const v = new Date(dados.dataVencimento + 'T12:00:00');",
  "    const hj = new Date(); hj.setHours(0,0,0,0);",
  "    if (v <= hj) { console.log('[BOLETO] Vencimento no passado, +30 dias'); dataVencimento = calcularDataVencimento(30); }",
  "  }",
  "  const etapa = dados.etapa || 'Simulacao';",
  "  const cpfCnpj = dados.cpfCnpjPagador || '';",
  "  const tipoPessoa = cpfCnpj.length <= 11 ? 'F' : 'J';",
  "  const campoPessoa = tipoPessoa === 'F' ? 'numero_cadastro_pessoa_fisica' : 'numero_cadastro_nacional_pessoa_juridica';",
  "  return {",
  "    etapa_processo_boleto: etapa,",
  "    beneficiario: { id_beneficiario: idBeneficiario },",
  "    dado_boleto: {",
  "      descricao_instrumento_cobranca: 'boleto_pix',",
  "      tipo_boleto: 'a vista',",
  "      texto_seu_numero: String(dados.numeroPedido || '000001').substring(0, 10),",
  "      codigo_carteira: dados.codigoCarteira || codigoCarteira,",
  "      codigo_especie: '01',",
  "      data_emissao: getDataHoje(),",
  "      valor_abatimento: '00000000000000000',",
  "      pagador: {",
  "        pessoa: {",
  "          nome_pessoa: dados.nomePagador || '',",
  "          tipo_pessoa: { codigo_tipo_pessoa: tipoPessoa }",
  "        },",
  "        endereco: {",
  "          nome_logradouro: dados.logradouro || 'Rua Nao Informada',",
  "          nome_bairro: dados.bairro || 'Nao Informado',",
  "          nome_cidade: dados.cidade || 'Nao Informado',",
  "          sigla_UF: dados.estado || 'SP',",
  "          numero_CEP: String(dados.cep || '00000000').replace(/[^0-9]/g, '')",
  "        }",
  "      },",
  "      dados_individuais_boleto: [{",
  "        numero_nosso_numero: nossoNumero,",
  "        data_vencimento: dataVencimento,",
  "        texto_uso_beneficiario: String(dados.numeroPedido || '000001').substring(0, 25),",
  "        valor_titulo: formatarValorItau(dados.valor),",
  "        texto_seu_numero: String(dados.numeroPedido || '000001').substring(0, 10),",
  "        data_limite_pagamento: dataVencimento",
  "      }]",
  "    },",
  "    dados_qrcode: { chave: config.itau.pixChave || dados.chavePix || '' }",
  "  };",
  "}",
  "",
  "async function emitirBoleto(dados) {",
  "  console.log('[BOLETO] Iniciando emissao... Valor:', dados.valor, 'CPF:', dados.cpfCnpjPagador);",
  "  let accessToken;",
  "  try { accessToken = await getAccessToken(); }",
  "  catch (err) { throw new Error('Falha autenticacao: ' + err.message); }",
  "  const payload = montaPayloadBolecode(dados);",
  "  console.log('[BOLETO] Etapa:', payload.etapa_processo_boleto);",
  "  console.log('[BOLETO] Payload:', JSON.stringify(payload, null, 2));",
  "  try {",
  "    const response = await callBolecode(accessToken, '/boletos_pix', payload);",
  "    console.log('[BOLETO] SUCESSO! Resposta:', JSON.stringify(response, null, 2));",
  "    return { sucesso: true, dados: response };",
  "  } catch (error) {",
  "    if (error.message && (error.message.includes('401') || error.message.includes('403'))) {",
  "      console.log('[BOLETO] Token expirado, tentando novamente...');",
  "      invalidateToken();",
  "      try {",
  "        accessToken = await getAccessToken();",
  "        const r = await callBolecode(accessToken, '/boletos_pix', payload);",
  "        console.log('[BOLETO] SUCESSO na 2a tentativa!');",
  "        return { sucesso: true, dados: r };",
  "      } catch (e) { throw e; }",
  "    }",
  "    throw error;",
  "  }",
  "}",
  "",
  "module.exports = { emitirBoleto, montaPayloadBolecode };",
]);

w('services/itau-api.js', [
  "const axios = require('axios');",
  "const https = require('https');",
  "const config = require('../config');",
  "",
  "async function callBolecode(accessToken, endpoint, payload) {",
  "  const mtls = config.createMtlsConfig();",
  "  const baseUrl = config.itau.bolecodeBaseUrl;",
  "  const httpsAgent = mtls.hasMtls ? new https.Agent({ cert: mtls.cert, key: mtls.key }) : undefined;",
  "  const url = baseUrl + endpoint;",
  "  console.log('[ITAU-API] BoleCode POST', endpoint);",
  "  const headers = {",
  "    'Authorization': 'Bearer ' + accessToken,",
  "    'Content-Type': 'application/json; charset=utf-8',",
  "    'Accept': 'application/json',",
  "    'x-itau-apikey': config.itau.clientId,",
  "    'x-itau-correlationID': String(Date.now()),",
  "  };",
  "  try {",
  "    const response = await axios.post(url, payload, { headers, httpsAgent, timeout: 30000 });",
  "    return response.data;",
  "  } catch (error) {",
  "    if (error.response) {",
  "      const msg = JSON.stringify(error.response.data);",
  "      console.error('[ITAU-API] ERRO ' + error.response.status + ':', msg);",
  "      throw new Error('BoleCode ' + error.response.status + ': ' + msg);",
  "    }",
  "    throw new Error('BoleCode conexao: ' + error.message);",
  "  }",
  "}",
  "",
  "module.exports = { callBolecode };",
]);

w('config/index.js', [
  "require('dotenv').config();",
  "const config = {",
  "  port: process.env.PORT || 3000,",
  "  nodeEnv: process.env.NODE_ENV || 'development',",
  "  isRender: process.env.RENDER === 'true',",
  "  apiSecretKey: process.env.API_SECRET_KEY || '',",
  "  itau: {",
  "    clientId: process.env.ITAU_CLIENT_ID || '',",
  "    clientSecret: process.env.ITAU_CLIENT_SECRET || '',",
  "    tokenUrl: process.env.ITAU_TOKEN_URL || 'https://sts.itau.com.br/api/oauth/token',",
  "    bolecodeBaseUrl: process.env.ITAU_BOLECODE_URL || 'https://secure.api.itau/pix_recebimentos_conciliacoes/v2',",
  "    pixChave: process.env.ITAU_PIX_CHAVE || '',",
  "  },",
  "  banco: {",
  "    agencia: process.env.ITAU_AGENCIA || '7764',",
  "    conta: process.env.ITAU_CONTA || '22338-9',",
  "    idBeneficiario: process.env.ITAU_ID_BENEFICIARIO || '776400223389',",
  "    codigoCarteira: process.env.ITAU_CARTEIRA || '109',",
  "  },",
  "  empresa: {",
  "    cnpj: process.env.EMPRESA_CNPJ || '22603750000190',",
  "    nome: process.env.EMPRESA_NOME || 'AJL FERRO E ACO LTDA',",
  "  },",
  "  mtls: {",
  "    cert: process.env.ITAU_CERT_CRT || '',",
  "    key: process.env.ITAU_CERT_KEY || '',",
  "  },",
  "  createMtlsConfig() {",
  "    const hasCert = !!(this.mtls.cert && this.mtls.key);",
  "    if (!hasCert) return { cert: null, key: null, hasMtls: false };",
  "    return { cert: this.mtls.cert, key: this.mtls.key, hasMtls: true };",
  "  },",
  "};",
  "if (!config.itau.pixChave) console.warn('[CONFIG] ITAU_PIX_CHAVE nao definida!');",
  "module.exports = config;",
]);

w('routes/api.js', [
  "const express = require('express');",
  "const router = express.Router();",
  "const { authenticateApiKey } = require('../middleware/auth');",
  "const { emitirBoleto } = require('../services/itau-boleto');",
  "",
  "router.post('/pagar', authenticateApiKey, async (req, res) => {",
  "  try {",
  "    const d = req.body;",
  "    console.log('[API] Body:', JSON.stringify(d));",
  "    const fat = d.fatura || {};",
  "    const pag = d.pagador || {};",
  "    const payload = {",
  "      valor: fat.valor_nominal || d.valor || d.amount,",
  "      cpfCnpjPagador: pag.cpf_cnpj || d.cpfCnpj || '',",
  "      nomePagador: pag.nome || d.nome || '',",
  "      numeroPedido: fat.seu_numero || fat.name || '',",
  "      dataVencimento: fat.data_vencimento || '',",
  "      logradouro: pag.street || '',",
  "      bairro: pag.bairro || '',",
  "      cidade: pag.city || '',",
  "      estado: pag.state || '',",
  "      cep: pag.zip || '',",
  "    };",
  "    console.log('[API] Payload:', JSON.stringify(payload));",
  "    const resultado = await emitirBoleto(payload);",
  "    res.json({ sucesso: true, mensagem: 'Boleto emitido', dados: resultado.dados });",
  "  } catch (error) {",
  "    console.error('Erro middleware:', error.message);",
  "    res.status(500).json({ sucesso: false, erro: error.message });",
  "  }",
  "});",
  "",
  "module.exports = router;",
]);

console.log(''); console.log('v6.2 aplicada com sucesso!'); console.log('');
